---
- name: Ansible lab
  hosts: local
  gather_facts: true

  tasks:
    - name: Install some basic packages defined in variable "packages"
      become: true
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - nginx
          - openjdk-8-jre

    - name: Enable Nginx service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Create {{ app_dir }} directory if it does not exist
      become: true
      ansible.builtin.file:
        path: "{{ app_dir }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        mode: '0755'

    - name: Download Java app to {{ app_dir }}/{{ app_file }}
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/devops-practice-files/systemd/ServicesLab-0.0.1.jar"
        dest: "{{ app_dir }}/{{ app_file }}"
        owner: "{{ ansible_user_id }}"
        mode: '0644'

    - name: Create a Java App Unit
      become: true
      notify:
        - Reload Systemd
      ansible.builtin.template:
        src: "app.service.j2"
        dest: "/etc/systemd/system/sample.service"
        mode: '0644'
        owner: root
        group: root

    - name: Enable sample.service, ensure it is not masked and start it
      become: true
      ansible.builtin.systemd:
        name: sample
        state: started
        enabled: yes

    - name: Create a Nginx config
      become: true
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/nginx.conf"
        mode: '0644'
        owner: root
        group: root

    - name: Restart Nginx
      become: true
      ansible.builtin.systemd:
        name: nginx
        state: restarted

  handlers:
    - name: Reload Systemd
      become: true
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: reloaded
      with_items:
        - sample
        - nginx